### ISSUE TITLE
Working with file paths

### ISSUE THREAD

**Issue by jrhooker** [chrispy-snps/pdf-annotate-change-bars#1]
First, this is frikkin' brilliant. I've had users of my XML CCMS asking for this feature in output PDFs for years.

Getting it working was easy, but since I know exactly zero Python, I'm not sure how to hack it to allow it to accept paths to and from the target and output PDFs instead of having to work exclusively from the same directory as the .pl file. I'm on CentOS; got any guidance for me? When I try to feed it a path instead of simply a filename it dies on line 95.

Cheers.

**Comment by chrispy-snps** [comment]
I'm glad it's useful for you!

It looks like I didn't support paths in the arguments at all. (This was pretty much a hack script that I decided to share.) I committed a fix. Can you pull the current version and try again?

**Comment by jrhooker** [comment]
Works beautifully, thanks! I administrate an XML CCMS at a semiconductor design company. Years ago I built the ability to diff very large design specs using DeltaXML and while the engineers love the precision diffing, having to scroll through every page of a 2000 page PDF to find all the changes has been a consistent pain point. That just went away. It's awesome.

**Comment by chrispy-snps** [comment]
@jrhooker - are you interested in testing a rewrite of this script? It now analyzes the innards of the PDF file instead of rasterizing it, which is much faster.
